/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mazepart1;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String nameCharacter="Knight";
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        XStart = new javax.swing.JTextField();
        YStart = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        knightbutton = new javax.swing.JRadioButton();
        snakebutton = new javax.swing.JRadioButton();
        hippobutton = new javax.swing.JRadioButton();
        tigerbutton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        XEnd = new javax.swing.JTextField();
        YEnd = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        XStart.setText("A");
        XStart.setToolTipText("");
        XStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XStartActionPerformed(evt);
            }
        });
        getContentPane().add(XStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 526, 37, -1));

        YStart.setText("1");
        YStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YStartActionPerformed(evt);
            }
        });
        getContentPane().add(YStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 37, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 110, 50));

        jPanel1.setMinimumSize(new java.awt.Dimension(829, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 11, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Pick your hero :");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/snake.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 167));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hippopotamus.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiger.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crusader.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 144, -1, -1));

        buttonGroup.add(knightbutton);
        knightbutton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        knightbutton.setSelected(true);
        knightbutton.setText("KNIGHT");
        knightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knightbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(knightbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        buttonGroup.add(snakebutton);
        snakebutton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        snakebutton.setText("SNAKE");
        snakebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snakebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(snakebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        buttonGroup.add(hippobutton);
        hippobutton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        hippobutton.setText("HIPPOPOTAMUS");
        hippobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hippobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(hippobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        tigerbutton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tigerbutton.setText("TIGER");
        tigerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigerbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(tigerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to the maze !");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 250, 65));

        jLabel13.setBackground(new java.awt.Color(0, 0, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Water");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 324, 73, -1));

        jLabel14.setBackground(new java.awt.Color(255, 153, 51));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Sand");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 359, 73, -1));

        jLabel15.setBackground(new java.awt.Color(255, 153, 153));
        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Montains");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 394, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 204, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Forest");
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 429, 73, -1));

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("Road");
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 464, 73, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("5");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 324, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("4");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 359, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("6");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 394, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("4");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 429, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setText("1");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 464, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setText("2");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel24.setText("1");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setText("N/A");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel26.setText("3");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setText("3");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setText("1");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel29.setText("4");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setText("N/A");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel31.setText("5");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel32.setText("2");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel33.setText("N/A");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel34.setText("4");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel35.setText("2");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel36.setText("1");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel37.setText("3");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setOpaque(true);
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 740, 380));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel2.setText("Choose the start coordonates");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 529, -1, -1));

        jLabel4.setText("X Start (A-J)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 529, -1, -1));

        jLabel5.setText("Y Start (1-10)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        jLabel10.setText("Choose the end coordonates");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 529, -1, -1));

        jLabel11.setText("X End (A-J)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        jLabel12.setText("Y End (1-10)");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        XEnd.setText("J");
        XEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XEndActionPerformed(evt);
            }
        });
        getContentPane().add(XEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 34, -1));

        YEnd.setText("10");
        getContentPane().add(YEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 34, -1));

        jLabel40.setBackground(new java.awt.Color(204, 204, 204));
        jLabel40.setOpaque(true);
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 511, 800, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void XStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XStartActionPerformed

    private void XEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XEndActionPerformed

    private void snakebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snakebuttonActionPerformed
        // TODO add your handling code here:
        System.out.println("you selected snake");
        nameCharacter="Snake";
    }//GEN-LAST:event_snakebuttonActionPerformed

    private void hippobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hippobuttonActionPerformed
        // TODO add your handling code here:
        System.out.println("you selected hippopotamus");
        nameCharacter="Hippopotame";
    }//GEN-LAST:event_hippobuttonActionPerformed

    private void tigerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigerbuttonActionPerformed
        // TODO add your handling code here:
        System.out.println("you selected tiger");
        nameCharacter="Tiger";
    }//GEN-LAST:event_tigerbuttonActionPerformed

    private void knightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knightbuttonActionPerformed
        // TODO add your handling code here:
        System.out.println("you selected knight");
        nameCharacter="Knight";
    }//GEN-LAST:event_knightbuttonActionPerformed

    public static boolean isStringOnlyAlphabet(String str) 
    { 
        return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^[A-J]*$"))); 
    }
    
    public static boolean isNumberOfInterval (String str) 
    { 
        return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^(1[0]|[1-9])$"))); 
    } 
    
    public class IncorrectCoordonateException extends RuntimeException { 
        public IncorrectCoordonateException(String errorMessage) {
            super(errorMessage);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String xCoordStart = XStart.getText();
        
        if(isStringOnlyAlphabet(xCoordStart) == false){
            JFrame errorFrame = new JFrame("showMessageDialog");
            errorFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(errorFrame, xCoordStart + " is not between A and J", "Error window", JOptionPane.INFORMATION_MESSAGE);
            throw new IncorrectCoordonateException(xCoordStart + " is not between A and J");
        }
        int num1 = 0;
        switch (xCoordStart) {
            case "A":
                num1 = 73;
                break;
            case "B":
                num1 = 93;
                break;
            case "C":
                num1 = 113;
                break;
            case "D":
                num1 = 133;
                break;
            case "E":
                num1 = 153;
                break;
            case "F":
                num1 = 173;
                break;
            case "G":
                num1 = 193;
                break;
            case "H":
                num1 = 213;
                break;
            case "I":
                num1 = 233;
                break;
            case "J":
                num1 = 253;
                break;

            default:
            // code block
        }
        String yCoordStart = YStart.getText();
        int num2 = Integer.parseInt(yCoordStart);
        if(isNumberOfInterval(yCoordStart) == false){
            JFrame errorFrame = new JFrame("showMessageDialog");
            errorFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(errorFrame, yCoordStart + " is not between 1 and 10", "Error window", JOptionPane.INFORMATION_MESSAGE);
            throw new IncorrectCoordonateException(yCoordStart + " is not between 1 and 10");
        }
        switch (num2) {
            case 1:
                num2 = 83;
                break;
            case 2:
                num2 = 103;
                break;
            case 3:
                num2 = 123;
                break;
            case 4:
                num2 = 143;
                break;
            case 5:
                num2 = 163;
                break;
            case 6:
                num2 = 183;
                break;
            case 7:
                num2 = 203;
                break;
            case 8:
                num2 = 223;
                break;
            case 9:
                num2 = 243;
                break;
            case 10:
                num2 = 263;
                break;

            default:
            // code block
        }
        String sum = xCoordStart + yCoordStart;
        String xCoordEnd = XEnd.getText();
        
        if(isStringOnlyAlphabet(xCoordEnd) == false){
            JFrame errorFrame = new JFrame("showMessageDialog");
            errorFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(errorFrame, xCoordEnd + " is not between A and J", "Error window", JOptionPane.INFORMATION_MESSAGE);
            throw new IncorrectCoordonateException(xCoordEnd + " is not between A and J");
        }
        int num3 = 0;
        switch (xCoordEnd) {
            case "A":
                num3 = 73;
                break;
            case "B":
                num3 = 93;
                break;
            case "C":
                num3 = 113;
                break;
            case "D":
                num3 = 133;
                break;
            case "E":
                num3 = 153;
                break;
            case "F":
                num3 = 173;
                break;
            case "G":
                num3 = 193;
                break;
            case "H":
                num3 = 213;
                break;
            case "I":
                num3 = 233;
                break;
            case "J":
                num3 = 253;
                break;

            default:
            // code block
        }
        String yCoordEnd = YEnd.getText();
        int num4 = Integer.parseInt(yCoordEnd);
        if(isNumberOfInterval(yCoordEnd) == false){
            JFrame errorFrame = new JFrame("showMessageDialog");
            errorFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(errorFrame, yCoordEnd + " is not between 1 and 10", "Error window", JOptionPane.INFORMATION_MESSAGE);
            throw new IncorrectCoordonateException(yCoordEnd + " is not between 1 and 10");
        }
        switch (num4) {
            case 1:
                num4 = 83;
                break;
            case 2:
                num4 = 103;
                break;
            case 3:
                num4 = 123;
                break;
            case 4:
                num4 = 143;
                break;
            case 5:
                num4 = 163;
                break;
            case 6:
                num4 = 183;
                break;
            case 7:
                num4 = 203;
                break;
            case 8:
                num4 = 223;
                break;
            case 9:
                num4 = 243;
                break;
            case 10:
                num4 = 263;
                break;

            default:
            // code block
        }
        String sum2 = xCoordEnd + yCoordEnd;
        ArrayList<String> bricks = MazePart1.read("data/MazeMap.txt");

        Form window = new Form(bricks, num1, num2, num3 + 3, num4 + 12,nameCharacter);
        window.setTitle("Maze");
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void YStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    static ArrayList<String> read(String filename) {
        ArrayList<String> lines = new ArrayList<>();
        try {
            FileInputStream fstream = new FileInputStream(filename);
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String line;

            while ((line = br.readLine()) != null) {
                if (line.length() != 26) {
                    lines.add(line);
                } else {
                    System.err.println("Incorect lenght in the .txt file");
                    System.err.println(line.length());
                    System.exit(0);
                }

            }

            in.close();
        } catch (Exception e) {
            System.err.println("Error :" + e.getMessage());
        }

        if (lines.size() != 13) {
            System.err.println("Incorrect number of lines in the .txt file");
            System.exit(0);
        }
        return lines;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField XEnd;
    private javax.swing.JTextField XStart;
    private javax.swing.JTextField YEnd;
    private javax.swing.JTextField YStart;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton hippobutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton knightbutton;
    private javax.swing.JRadioButton snakebutton;
    private javax.swing.JRadioButton tigerbutton;
    // End of variables declaration//GEN-END:variables
}
